# Generated by Django 2.2 on 2020-01-31 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetails',
            options={'verbose_name': 'User Details'},
        ),
    ]
